// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awmszxrtommgxjnivddq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3bXN6eHJ0b21tZ3hqbml2ZGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzMzMDQsImV4cCI6MjA2NTU0OTMwNH0.6z6K_tW5YKdrbxTsTPy2BsjB3h0FwjmXtWeq2d5GPRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);